### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by bradydjohnson** [ThePornDatabase/stash_theporndb_scraper#51]
When I try to run scrapeScenes.py, it returns

```
  File "/Users/bradyjohnson/Downloads/stash_theporndb_scraper-master/scrapeScenes.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by Darklyter** [comment]
You need to install the python requests module, since it looks like it isn't in your path.
https://www.geeksforgeeks.org/how-to-install-requests-in-python-for-windows-linux-mac/

**Comment by bradydjohnson** [comment]
Thank you!
